/**
 * Apache Guacamole gateway integration. v1 path: file-based
 * user-mapping.xml maintained from the DB. The control-plane is the
 * single writer of the XML file; Guacamole re-reads it on every login,
 * so no service reload / restart is required when a connection is
 * added or removed.
 *
 * Connection model (one per LabInstance):
 *   - login user/password are random per-instance, stored on the
 *     LabInstance row and only revealed to the redeem flow when it
 *     constructs the auto-login URL
 *   - the user has exactly ONE connection, named after the instance,
 *     pointing at <node.proxyHost>:<instance.rdpHostPort> with the
 *     template's RDP creds baked in
 *
 * Redeem path:
 *   ensureConnection(instance) -> regenerateUserMapping(...) ->
 *   redirect to clientUrl(instance, gconf)
 *
 * Destroy path:
 *   labInstance row already has guacamoleUser cleared by the caller
 *   before regenerateUserMapping(...) is called again.
 */
import { randomBytes } from 'node:crypto';
import { writeFile, rename, mkdir } from 'node:fs/promises';
import { dirname } from 'node:path';
import type {
  GuacamoleConfig,
  LabInstance,
  LabTemplate,
  Node,
  PrismaClient,
} from '@prisma/client';
import { LabTemplateSpec, type LabTemplateSpec as LabTemplateSpecT } from '@labforge/shared';
import { nodeExec } from './nodeShell.js';

/**
 * Generate a URL-safe random string. 24 bytes of entropy → 32 chars
 * after base64url, plenty for a per-instance password.
 */
function randToken(bytes = 24): string {
  return randomBytes(bytes)
    .toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=+$/, '');
}

/**
 * Mint per-instance Guacamole login creds and persist them on the row.
 * Idempotent: if the row already has creds, returns them unchanged so
 * resume/redeem cycles keep the same URL valid.
 */
export async function ensureGuacamoleCredentials(
  prisma: PrismaClient,
  instanceId: string,
): Promise<{ user: string; password: string }> {
  const inst = await prisma.labInstance.findUnique({
    where: { id: instanceId },
    select: { guacamoleUser: true, guacamolePassword: true },
  });
  if (!inst) {
    throw new Error(`ensureGuacamoleCredentials: instance ${instanceId} not found`);
  }
  if (inst.guacamoleUser && inst.guacamolePassword) {
    return { user: inst.guacamoleUser, password: inst.guacamolePassword };
  }
  // 12 bytes of base64url == 16 chars, plenty for the username — and we
  // namespace with `lab-` so an operator browsing the file can tell
  // these are control-plane managed.
  const user = `lab-${randToken(12)}`;
  const password = randToken(24);
  await prisma.labInstance.update({
    where: { id: instanceId },
    data: { guacamoleUser: user, guacamolePassword: password },
  });
  return { user, password };
}

/**
 * Clear an instance's Guacamole creds. Called from destroyInstance()
 * before the user-mapping is re-rendered so the entry vanishes from
 * the file.
 */
export async function clearGuacamoleCredentials(
  prisma: PrismaClient,
  instanceId: string,
): Promise<void> {
  await prisma.labInstance.update({
    where: { id: instanceId },
    data: { guacamoleUser: null, guacamolePassword: null },
  });
}

interface RenderRow {
  instance: LabInstance;
  template: LabTemplate;
  node: Node | null;
  spec: LabTemplateSpecT;
}

function escapeXmlAttr(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

/**
 * Render the entire user-mapping.xml from the current set of live
 * Guacamole-enabled lab instances. Layout:
 *
 *   <user-mapping>
 *     <authorize username="lab-<id>" password="<pw>">
 *       <connection name="<instanceId>">
 *         <protocol>rdp</protocol>
 *         <param name="hostname">…</param>
 *         <param name="port">…</param>
 *         <param name="username">Docker</param>
 *         <param name="password">…</param>
 *         <param name="security">any</param>
 *         <param name="ignore-cert">true</param>
 *       </connection>
 *     </authorize>
 *   </user-mapping>
 *
 * Each authorize block has exactly one connection — the auto-login
 * URL with that user lands the student straight on their lab.
 */
export function renderUserMappingXml(rows: RenderRow[], gconf: GuacamoleConfig): string {
  const lines: string[] = [];
  lines.push('<?xml version="1.0" encoding="UTF-8"?>');
  lines.push('<!-- AUTOGENERATED by labforge control-plane. Do not edit by hand. -->');
  lines.push('<user-mapping>');
  for (const r of rows) {
    if (!r.instance.guacamoleUser || !r.instance.guacamolePassword) continue;
    if (!r.instance.rdpHostPort) continue;
    if (!r.spec.rdpUsername) continue;
    const host =
      r.node?.proxyHost && r.node.proxyHost.length > 0
        ? r.node.proxyHost
        : gconf.defaultRdpHost ?? '';
    if (!host) continue;
    lines.push(
      `  <authorize username="${escapeXmlAttr(r.instance.guacamoleUser)}" ` +
        `password="${escapeXmlAttr(r.instance.guacamolePassword)}">`,
    );
    lines.push(`    <connection name="${escapeXmlAttr(r.instance.id)}">`);
    lines.push('      <protocol>rdp</protocol>');
    lines.push(`      <param name="hostname">${escapeXmlAttr(host)}</param>`);
    lines.push(`      <param name="port">${String(r.instance.rdpHostPort)}</param>`);
    lines.push(`      <param name="username">${escapeXmlAttr(r.spec.rdpUsername)}</param>`);
    if (r.spec.rdpPassword) {
      lines.push(`      <param name="password">${escapeXmlAttr(r.spec.rdpPassword)}</param>`);
    }
    // 'any' lets guacd negotiate (NLA → TLS → RDP) so it works across
    // dockur/windows builds that vary in supported security layers.
    // Forcing 'nla' was rejected by Win11 builds we tested ("wrong
    // security type?"). 'any' is what Guacamole's own docs recommend
    // when the back-end RDP stack isn't fully under your control.
    lines.push('      <param name="security">any</param>');
    lines.push('      <param name="ignore-cert">true</param>');
    lines.push('      <param name="resize-method">display-update</param>');
    lines.push('      <param name="enable-wallpaper">false</param>');
    lines.push('      <param name="enable-theming">false</param>');
    lines.push('      <param name="enable-font-smoothing">true</param>');
    lines.push('      <param name="color-depth">24</param>');
    lines.push('    </connection>');
    lines.push('  </authorize>');
  }
  lines.push('</user-mapping>');
  return lines.join('\n') + '\n';
}

async function writeUserMappingLocal(path: string, body: string): Promise<void> {
  await mkdir(dirname(path), { recursive: true });
  const tmp = `${path}.${randToken(6)}.tmp`;
  // 0o644 (world-readable) is required: the guacamole container runs as
  // uid 1000 (`guacamole` user) and reads this file via a bind mount,
  // while the control-plane writes it as root. Without world read the
  // tomcat process cannot load the user-mapping and crash-loops.
  await writeFile(tmp, body, { mode: 0o644 });
  await rename(tmp, path);
}

async function writeUserMappingRemote(
  gconf: GuacamoleConfig,
  body: string,
): Promise<void> {
  if (!gconf.userMappingPath) {
    throw new Error('writeUserMappingRemote: userMappingPath is null');
  }
  // Reuse the nodeExec ssh helper by synthesizing a minimal Node-shaped
  // object. This avoids a second SSH stack and keeps connection caching
  // in one place. We pass `connectionMode: 'ssh'` so it goes over ssh2.
  const fakeNode: Node = {
    id: '__guacamole__',
    name: '__guacamole__',
    isDefault: false,
    connectionMode: 'ssh',
    sshHost: gconf.sshHost,
    sshUser: gconf.sshUser,
    sshPort: gconf.sshPort,
    sshKeyPath: gconf.sshKeyPath,
    sshPassword: gconf.sshPassword,
    proxyHost: '127.0.0.1',
    bindIp: '0.0.0.0',
    capacityMax: 0,
    enabled: true,
    notes: null,
    lastSeenAt: null,
    lastError: null,
    dockerVersion: null,
    createdAt: new Date(),
    updatedAt: new Date(),
  };
  // Stage to a tmp file then atomic rename. base64-encode the body so
  // single quotes / newlines inside the XML can't terminate the heredoc.
  // Mode 0644 — see writeUserMappingLocal for rationale.
  const b64 = Buffer.from(body, 'utf8').toString('base64');
  const tmp = `${gconf.userMappingPath}.${randToken(6)}.tmp`;
  // shell-quote the paths
  const q = (s: string) => `'${s.replace(/'/g, `'\\''`)}'`;
  const cmd = [
    `mkdir -p ${q(dirname(gconf.userMappingPath))}`,
    `printf %s ${q(b64)} | base64 -d > ${q(tmp)}`,
    `chmod 644 ${q(tmp)}`,
    `mv ${q(tmp)} ${q(gconf.userMappingPath)}`,
  ].join(' && ');
  const res = await nodeExec(fakeNode, cmd);
  if (res.exitCode !== 0) {
    throw new Error(
      `guacamole user-mapping remote write failed: code=${res.exitCode} ` +
        `stderr=${res.stderr.trim().slice(0, 400)}`,
    );
  }
}

/**
 * Atomically write the file at `gconf.userMappingPath`. Local when
 * `gconf.sshHost` is null/empty, otherwise SSHes to the Guacamole host.
 */
export async function writeUserMapping(
  gconf: GuacamoleConfig,
  body: string,
): Promise<void> {
  if (!gconf.userMappingPath) {
    throw new Error('writeUserMapping: GuacamoleConfig.userMappingPath is not set');
  }
  if (gconf.sshHost && gconf.sshHost.length > 0) {
    await writeUserMappingRemote(gconf, body);
  } else {
    await writeUserMappingLocal(gconf.userMappingPath, body);
  }
}

/** Load the singleton config row, or null when not yet configured. */
export async function loadGuacamoleConfig(
  prisma: PrismaClient,
): Promise<GuacamoleConfig | null> {
  return prisma.guacamoleConfig.findUnique({ where: { id: 'singleton' } });
}

/**
 * In-process serialisation for regenerateUserMapping. Without this, two
 * concurrent provision-success callbacks both:
 *   1. read DB snapshot,
 *   2. render XML,
 *   3. atomic-rename onto the file.
 * The atomic rename only protects against partial reads — it does NOT
 * protect against an *earlier-snapshot* writer winning the rename race
 * after a *later-snapshot* writer. The result is a stale user-mapping
 * missing entries for the newest ready instances. We saw this live with
 * 5 simultaneous launches → 3 entries on disk.
 *
 * The mutex coalesces overlapping calls: each new caller waits on the
 * in-flight chain, so by the time it runs its DB read it sees every
 * commit that happened before it started waiting. Cheap, in-process,
 * good enough for a single control-plane node. (For HA we'd swap this
 * for a Postgres advisory lock keyed on guacamole_singleton.)
 */
let regenChain: Promise<unknown> = Promise.resolve();

/**
 * Re-render and ship the entire user-mapping.xml. Call after any state
 * change that affects what should be in the file (provision success,
 * destroy, manual cred rotation). No-op when GuacamoleConfig is missing
 * or disabled — operators can keep the rest of the platform running
 * while they finish wiring the gateway.
 *
 * Concurrent calls are serialised in-process (see regenChain above) so
 * the latest committer always wins the file.
 */
export async function regenerateUserMapping(
  prisma: PrismaClient,
): Promise<{ rendered: number; written: boolean }> {
  const next = regenChain.then(() => regenerateUserMappingInner(prisma));
  // Don't propagate failures along the chain — each caller awaits its
  // own result, but the chain itself must keep going so a transient SSH
  // hiccup doesn't poison every subsequent regen.
  regenChain = next.catch(() => undefined);
  return next;
}

async function regenerateUserMappingInner(
  prisma: PrismaClient,
): Promise<{ rendered: number; written: boolean }> {
  const gconf = await loadGuacamoleConfig(prisma);
  if (!gconf || !gconf.enabled || !gconf.userMappingPath) {
    return { rendered: 0, written: false };
  }
  // We want every "user-visible" instance regardless of suspend state —
  // a paused lab still has a valid Guacamole entry; redeem will resume
  // it and the entry's hostname/port are still correct.
  const instances = await prisma.labInstance.findMany({
    where: {
      guacamoleUser: { not: null },
      status: { notIn: ['terminated', 'failed'] },
    },
    include: { template: true, node: true },
  });
  const rows: RenderRow[] = [];
  for (const inst of instances) {
    let spec: LabTemplateSpecT;
    try {
      spec = LabTemplateSpec.parse(inst.template.spec);
    } catch {
      continue;
    }
    rows.push({ instance: inst, template: inst.template, node: inst.node, spec });
  }
  const body = renderUserMappingXml(rows, gconf);
  await writeUserMapping(gconf, body);
  return { rendered: rows.length, written: true };
}

/**
 * Build the URL the redeem flow redirects the student to. Uses the
 * deprecated-but-still-supported `?username=&password=` query auth so
 * the student lands directly on their (single) connection without a
 * login screen.
 *
 * Format: `<publicUrl>/guacamole/?username=<u>&password=<p>` —
 * Guacamole's file-auth provider accepts these parameters and the
 * single-connection user-mapping makes auto-connect implicit.
 */
export function guacamoleClientUrl(
  gconf: GuacamoleConfig,
  user: string,
  password: string,
): string {
  const base = gconf.publicUrl.replace(/\/+$/, '');
  const qs = new URLSearchParams({ username: user, password });
  return `${base}/guacamole/?${qs.toString()}`;
}
